name: mygetxchat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  cloud_firestore: 
  firebase_core: 
  firebase_auth: ^3.9.0
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.9
  firebase_messaging: ^13.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

